### ISSUE TITLE
Support specifying query parameters

### ISSUE THREAD

**Issue by johannesloher** [MaibornWolff/alt-core-js#34]
Currently, in REST actions, query parameters can only be specified by setting them as part of `endpoint`. This doesn't look very nice and is also not very flexible: It does not work well with overriding in scenarios.

This issue suggest to add the possibility to configure query parameters for REST actions by providing an additional optional field `queryParams`. If present, the members of this field get expanded to query parameters, like the following example describes:
```yaml
type: REST
service: my-service
endpoint: /api/users/search
method: GET
queryParams:
  userName: "Cliff Diver"
```
Performing this `action` will result in an HTTP call to
```
<base-url>/api/users/search?userName=Cliff%20Diver
```

It should be possible to use variables in `queryParams`:
```yaml
# search-user.yaml

type: REST
service: my-service
endpoint: /api/users/search
method: GET
queryParams:
  userName: "dummy username"
```
```yaml
# s1-search-user-scenario.yaml

description: "User search scenario"
variables:
  userNameToSearchFor: "Cliff Diver"
actions:
  - name: search-user
    queryParams:
      userName: {{userNameToSearchFor}}
```

Nesting in `queryParams` does not really make sense, because the values will be encoded as strings. I think it might still be viable to simply encode as JSON strings, if nesting is used:
```yaml
type: REST
service: my-service
endpoint: /api/users/search
method: GET
queryParams:
  user:
    name: "Cliff Diver"
```
will result in an HTTP call to
```
<base-url>/api/users/search?user=%7B%22name%22%3A%20%22Cliff%20Diver%22%7D
```
